id: I84975DB9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:04:55+00:00'
last_modified: '2022-06-09T06:10:43.465949+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1879
  title: ཁྲོ་ཕུ་ལོ་ཙྪ་བའི་རྣམ་ཐར་ཡབ་སྲས་མཇལ་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9AAA:
      image_group_id: I1CZ1963
      title: Volume 1 of khro phu lo ts+tsha ba'i rnam thar yab sras mjal ba
      total_pages: 28
      order: 1
      base_file: 9AAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
