id: P007119
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1879
  title: ཁྲོ་ཕུ་ལོ་ཙྪ་བའི་རྣམ་ཐར་ཡབ་སྲས་མཇལ་བ
  author: ''
  volumes:
    9e8697a607634956a2acafaa6fc0d2bc:
      image_group_id: I1CZ1963
      title: Volume 1 of khro phu lo ts+tsha ba'i rnam thar yab sras mjal ba
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
ebook_metadata:
  title: ཁྲོ་ཕུ་ལོ་ཙྪ་བའི་རྣམ་ཐར་ཡབ་སྲས་མཇལ་བ
  author: ''
  sku: P007119
  cover: cover.jpg
  layers:
  - pagination
