id: P007119
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1879
  title: ཁྲོ་ཕུ་ལོ་ཙྪ་བའི་རྣམ་ཐར་ཡབ་སྲས་མཇལ་བ
  author: ''
  volumes:
    a6c5ca09187d4508b975109aadca9204:
      image_group_id: I1CZ1963
      title: ''
      volume_number: 1
      total_pages: 28
ebook_metadata:
  title: ཁྲོ་ཕུ་ལོ་ཙྪ་བའི་རྣམ་ཐར་ཡབ་སྲས་མཇལ་བ
  author: ''
  sku: P007119
  cover: cover.jpg
  layers:
  - pagination
