id: P007119
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1879
  title: ཁྲོ་ཕུ་ལོ་ཙྪ་བའི་རྣམ་ཐར་ཡབ་སྲས་མཇལ་བ
  author: ''
  volumes:
    9e8697a607634956a2acafaa6fc0d2bc:
      image_group_id: I1CZ1963
      title: Volume 1 of khro phu lo ts+tsha ba'i rnam thar yab sras mjal ba
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
